# mongotools create minor from 'main' branch
name: mongotools-major
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: 'npmjs'
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Major
        run: |
          git config --global user.email  'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git fetch --all
          git checkout main
          npm version major
          git branch -f npmjs
          git push origin main npmjs --tags